@startuml

title __Bank Application Class Diagram__\n


abstract class BankAccount {
- accHolder: Person
    - accNum : int
    # balance : double
    + BankAccount()
    + BankAccount(accHolder: Person, accNum: int, balance: double)
    + describeAccount() : String
    }

class CurrentAccount {
+ describeAccount(): String
}

class StudentCurrentAccount {
+ describeAccount(): String
}

class GoldenYearsCurrentAccount {
+ describeAccount(): String
}

class OnlineCurrentAccount {
+ describeAccount(): String
}

class GraduateCurrentAccount {
+ describeAccount(): String
}

class PersonalCurrentAccount {
+ describeAccount(): String
}

class SavingsAccount {
+ describeAccount(): String
}

class StudentSavingsAccount {
+ describeAccount(): String
}

class GoldenYearsSavingsAccount {
+ describeAccount(): String
}

class OnlineSavingsAccount {
+ describeAccount(): String
}

class GraduateSavingsAccount {
+ describeAccount(): String
}

class PersonalSavingsAccount {
+ describeAccount(): String
}

class Person {
    - address : String
    - name : String
    + Person(name: String, address: String)
    + Person()
    + toString() : String
}

BankAccount o-- Person : has a
CurrentAccount -down-|> BankAccount
StudentCurrentAccount -down-|> BankAccount
GoldenYearsCurrentAccount -right-|> BankAccount
OnlineCurrentAccount -right-|> BankAccount
PersonalCurrentAccount -up-|> BankAccount
GraduateCurrentAccount -up-|> BankAccount
SavingsAccount -down-|> BankAccount
StudentSavingsAccount -down-|> BankAccount
GoldenYearsSavingsAccount -left-|> BankAccount
OnlineSavingsAccount -left-|> BankAccount
PersonalSavingsAccount -up-|> BankAccount
GraduateSavingsAccount -up-|> BankAccount

@enduml
